version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: passmate
      MYSQL_USER: devuser
      MYSQL_PASSWORD: khs08280
    volumes:
      - ./mysql_data:/var/lib/mysql